version: 2.1
jobs:
  codestyle:
    docker:
      - image: circleci/python:3.5
    environment:
      LANG: C.UTF-8
    steps:
      - checkout
      - run: pip install flake8
      - run: flake8 screamshotter
  package:
    docker:
      - image: ubuntu:bionic
    environment:
      LANG: C.UTF-8
      DEBIAN_FRONTEND: noninteractive
    steps:
      - checkout
      - run: >
          apt-get update && apt-get install -y dpkg-dev debhelper dh-virtualenv
          wget python3-all python3-venv libfontconfig1 libfreetype6 openssh-client
      - run: dpkg-buildpackage -uc -us -b
      # - run:
      #     command: scp ../screamshotter_*.deb server4.geotrek.ovh:www/ubuntu/bionic/
      #     when: on_success
workflows:
  version: 2
  all:
    jobs:
      - codestyle
      - package
